[package]
name = "algotoolkit-backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2"
pest_derive = "2"
z3 = "0.11.1"
uuid = "0.8.2"